credentials:
  usernames:
    euclid:
      email: euclid.ye@elwtech.com
      name: Euclid
      password: $2b$12$QT5l7FPhVHo0hYQuGGoRpu/f8jRJVbF2eHQOLn4HjAJBekXCX5hea #hashed for chatcx123

    chatcx:
      name: ChatCX Admin
      password: $2b$12$QT5l7FPhVHo0hYQuGGoRpu/f8jRJVbF2eHQOLn4HjAJBekXCX5hea #hashed for chatcx123
cookie:
  expiry_days: 30
  key: some_signature_key
  name: chatcx_euc_st
preauthorized: False
